### nesdemo2

NESDEMO2_SRCS:=nesdemo2.s
NESDEMO2_OBJS:=$(patsubst %.s,$(TARGET_DIR)/%.o,$(NESDEMO2_SRCS:%.c=$(TARGET_DIR)/%.o))
NESDEMO2_EXEC:=nesdemo2.nes
NESDEMO2_PRG:=$(TARGET_DIR)/nesdemo2.prg
NESDEMO2_CHR:=nesdemo2.chr

CLEAN_LIST+=$(NESDEMO2_OBJS) $(NESDEMO2_EXEC) $(NESDEMO2_PRG)

all :: $(NESDEMO2_EXEC)

$(NESDEMO2_PRG) : $(NESDEMO2_OBJS)

$(NESDEMO2_EXEC) : NESCOMBINE_FLAGS=-m 0
$(NESDEMO2_EXEC) : $(NESDEMO2_PRG) $(NESDEMO2_CHR)
